FROM postgres:15

# Установка cron и других утилит
RUN apt-get update && \
    apt-get install -y cron && \
    rm -rf /var/lib/apt/lists/*

# Копирование скрипта восстановления, начальных данных и настройки cron
COPY backup-cron /etc/cron.d/backup-cron

# Установка прав на выполнение для скриптов
RUN chmod 0644 /etc/cron.d/backup-cron

# Запуск cron и PostgreSQL
CMD ["sh", "-c", "cron && docker-entrypoint.sh postgres"]
