version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - loki
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: funnco
      SPRING_DATASOURCE_PASSWORD: funnco
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  db:
    build:
      context: .
      dockerfile: Dockerfile-db # Используем кастомный Dockerfile
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: funnco
      POSTGRES_PASSWORD: funnco
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-backups:/backups

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  db-data:
  db-backups:
  grafana-storage:
