version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
      - loki
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"

  db:
    build:
      context: ../../common
      dockerfile: Dockerfile-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data-stage:/var/lib/postgresql/data
      - db-backups-stage:/backups

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "${LOKI_PORT}:3100"

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-storage-stage:/var/lib/grafana

volumes:
  db-data-stage:
  db-backups-stage:
  grafana-storage-stage:
